/**
 * V1.6 — Path-based pre-auth tenant verify-email route.
 * Delegates to V1.5 UI; layout already injected the brand.
 * Reached via email link generated by API email-verification service.
 */
import VerifyEmailPage from '@/app/[locale]/(auth)/verify-email/page';
export default VerifyEmailPage;
