import {
  Calendar,
  ClipboardList,
  CreditCard,
  FileText,
  GraduationCap,
  LayoutDashboard,
  type LucideIcon,
  MessagesSquare,
  Megaphone,
  Building2,
  Users,
  UserPlus,
  Camera,
  Sparkles,
  Stethoscope,
  Bus,
  Utensils,
  ShieldAlert,
  Wallet,
  Settings,
  LogOut,
  Bell,
  Search,
  School,
  Shield,
  BookOpen,
  CalendarCheck,
  Scale,
  HeartHandshake,
} from 'lucide-react';

export const ICONS: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  establishment: Building2,
  schoolYear: Calendar,
  classes: School,
  students: Users,
  enrollments: UserPlus,
  teachers: GraduationCap,
  parents: HeartHandshake,
  notes: ClipboardList,
  bulletins: FileText,
  evaluations: BookOpen,
  journal: Camera,
  activities: Sparkles,
  absences: CalendarCheck,
  discipline: Scale,
  schedule: Calendar,
  canteen: Utensils,
  transport: Bus,
  health: Stethoscope,
  security: ShieldAlert,
  messages: MessagesSquare,
  announcements: Megaphone,
  payments: CreditCard,
  hrPayroll: Wallet,
  tenants: School,
  audit: Shield,
  branding: Settings,
  logout: LogOut,
  bell: Bell,
  search: Search,
};
