import {
  Calendar,
  ClipboardList,
  CreditCard,
  FileText,
  GraduationCap,
  LayoutDashboard,
  type LucideIcon,
  MessagesSquare,
  Megaphone,
  Building2,
  Users,
  UserPlus,
  Camera,
  Sparkles,
  Stethoscope,
  Bus,
  Utensils,
  ShieldAlert,
  Wallet,
  Settings,
  LogOut,
  Bell,
  Search,
  School,
  Shield,
  BookOpen,
  CalendarCheck,
  Scale,
  HeartHandshake,
  BookMarked,
  CalendarRange,
  UploadCloud,
  Receipt,
  Layers,
  AlertCircle,
  Banknote,
  ArchiveRestore,
  ShoppingCart,
  Truck,
  Eye,
  UtensilsCrossed,
  CalendarPlus,
  CalendarClock,
  CalendarDays,
  BarChart3,
} from 'lucide-react';

export const ICONS: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  establishment: Building2,
  schoolYear: Calendar,
  classes: School,
  students: Users,
  enrollments: UserPlus,
  teachers: GraduationCap,
  parents: HeartHandshake,
  notes: ClipboardList,
  bulletins: FileText,
  evaluations: BookOpen,
  journal: Camera,
  activities: Sparkles,
  absences: CalendarCheck,
  discipline: Scale,
  schedule: Calendar,
  canteen: Utensils,
  canteenDishes: UtensilsCrossed,
  canteenReservations: CalendarPlus,
  canteenStats: BarChart3,
  transport: Bus,
  health: Stethoscope,
  security: ShieldAlert,
  messages: MessagesSquare,
  announcements: Megaphone,
  payments: CreditCard,
  billing: CreditCard,
  hrPayroll: Wallet,
  tenants: School,
  audit: Shield,
  branding: Settings,
  imports: UploadCloud,
  logout: LogOut,
  bell: Bell,
  search: Search,
  subjects: BookMarked,
  gradePeriods: CalendarRange,
  feeTypes: Receipt,
  feeAssign: Layers,
  feeUnpaid: AlertCircle,
  cashRegister: Banknote,
  cashClosures: ArchiveRestore,
  expenses: ShoppingCart,
  suppliers: Truck,
  observations: Eye,
  appointments: CalendarClock,
  calendar: CalendarDays,
  classPromotion: GraduationCap,
};
