/**
 * V1.6 — Path-based pre-auth tenant reset-password route.
 * Delegates to V1.5 UI; layout already injected the brand.
 * Reached via email link generated by API password-recovery service.
 */
import ResetPasswordPage from '@/app/[locale]/(auth)/reset-password/page';
export default ResetPasswordPage;
